name = "iknow-vault"
compatibility_date = "2026-09-24"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "iknow-vault-db"
database_id = "4dad9e3e-07b6-4d22-a436-eef969598d4a"
