
const json=(x,init={})=>new Response(JSON.stringify(x),{headers:{'Content-Type':'application/json','Cache-Control':'no-store',...init.headers},...init.headers});
function valid(s,max=3000000){return typeof s==='string'&&s.length>0&&s.length<=max}
function fromB64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
function toB64(b){let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s)}
async function hashToken(t){return toB64(new Uint8Array(await crypto.subtle.digest('SHA-256',fromB64(t))))}
function equal(a,b){if(a.length!=b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
async function authorized(request,row){const h=request.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return false;const t=h.slice(7);return valid(t,500)&&equal(await hashToken(t),row.auth_verifier||'')}
export async function onRequestPost({request,env}){let b;try{b=await request.json()}catch{return json({error:'Invalid JSON'},{status:400})}if(!valid(b.salt,100)||!valid(b.iv,100)||!valid(b.ciphertext)||!valid(b.auth_verifier,100))return json({error:'Invalid payload'},{status:400});const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO vaults (id,salt,iv,ciphertext,auth_verifier,version,created_at,updated_at) VALUES (?,?,?,?,?,1,datetime('now'),datetime('now'))").bind(id,b.salt,b.iv,b.ciphertext,b.auth_verifier).run();return json({id},{status:201})}
export async function onRequestGet({request,env}){const id=new URL(request.url).searchParams.get('id');if(!id||id.length>100)return json({error:'Missing id'},{status:400});const row=await env.DB.prepare('SELECT id,salt,iv,ciphertext,auth_verifier,version FROM vaults WHERE id=?').bind(id).first();if(!row)return json({error:'Not found'},{status:404});if(!(await authorized(request,row)))return json({error:'Unauthorized'},{status:401});return json({id:row.id,salt:row.salt,iv:row.iv,ciphertext:row.ciphertext,version:row.version})}
export async function onRequestPut({request,env}){let b;try{b=await request.json()}catch{return json({error:'Invalid JSON'},{status:400})}if(!valid(b.id,100)||!valid(b.iv,100)||!valid(b.ciphertext)||!valid(b.auth_token,500)||!Number.isInteger(b.version)||b.version<1)return json({error:'Invalid payload'},{status:400});const row=await env.DB.prepare('SELECT auth_verifier,version FROM vaults WHERE id=?').bind(b.id).first();if(!row)return json({error:'Not found'},{status:404});if(!(await authorized(new Request(request.url,{headers:{authorization:'Bearer '+b.auth_token}}),row)))return json({error:'Unauthorized'},{status:401});const next=row.version+1;const r=await env.DB.prepare('UPDATE vaults SET iv=?,ciphertext=?,version=?,updated_at=datetime('now') WHERE id=? AND version=?').bind(b.iv,b.ciphertext,next,b.id,b.version).run();if(!r.meta?.changes)return json({error:'Vault changed elsewhere'},{status:409});return json({ok:true,version:next})}
